___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# SciPy

SciPy é uma coleção de algoritmos matemáticos e funções de conveniência construídas sob Numpy do Python. Ele adiciona poder significativo para a sessão interativa de Python, fornecendo ao usuário comandos e classes de alto nível para manipular e visualizar dados. Com o SciPy, uma sessão interativa de Python torna-se um ambiente de processamento de dados e prototipagem do sistema que rivaliza com sistemas como MATLAB, IDL, Octave, R-Lab e SciLab.

O benefício adicional de basar SciPy no Python é que isso também faz uma poderosa linguagem de programação disponível para o desenvolvimento de programas sofisticados e aplicativos especializados.

Tudo, desde programação paralela até sub-rotinas de base de dados e base de dados, foi disponibilizado ao programador Python. Todo esse poder está disponível além das bibliotecas matemáticas no SciPy.

Vamos focar muito mais nas matrizes NumPy, mas vamos mostrar algumas das capacidades do SciPy:

In [1]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,8]])

## Algebra Linear
**linalg**

In [2]:
from scipy import linalg

Determinante de uma matriz

In [3]:
# Calcule o determinante de uma matriz
linalg.det(A)

3.0

Calcule a decomposição de LU girada de uma matriz.

A decomposição é ::

    A = P L U

Onde P é uma matriz de permutação, L triangular inferior com elementos diagonais da unidade e U triangular superior.

In [4]:
P, L, U = linalg.lu(A)

In [5]:
P

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]])

In [6]:
L

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.14285714,  1.        ,  0.        ],
       [ 0.57142857,  0.5       ,  1.        ]])

In [7]:
U

array([[ 7.        ,  8.        ,  8.        ],
       [ 0.        ,  0.85714286,  1.85714286],
       [ 0.        ,  0.        ,  0.5       ]])

In [8]:
np.dot(L,U)

array([[ 7.,  8.,  8.],
       [ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

Podemos descobrir os autovalores e os vetores próprios desta matriz:

In [9]:
EW, EV = linalg.eig(A)

In [10]:
EW

array([ 15.55528261+0.j,  -1.41940876+0.j,  -0.13587385+0.j])

In [11]:
EV

array([[-0.24043423, -0.67468642,  0.51853459],
       [-0.54694322, -0.23391616, -0.78895962],
       [-0.80190056,  0.70005819,  0.32964312]])

A solução de sistemas de equações lineares também pode ser feita:

In [12]:
v = np.array([[2],[3],[5]])

In [13]:
v

array([[2],
       [3],
       [5]])

In [14]:
s = linalg.solve(A,v)

In [15]:
s

array([[-2.33333333],
       [ 3.66666667],
       [-1.        ]])

## Álgebra Linear Esparsa
SciPy possui algumas rotinas para computação com matrizes esparsas e potencialmente muito grandes. As ferramentas necessárias estão no submodulo scipy.sparse.

Nós fazemos um exemplo sobre como construir uma matriz grande:

In [16]:
from scipy import sparse

In [17]:
A = sparse.lil_matrix((1000, 1000))

In [18]:
A

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in LInked List format>

In [19]:
A[0,:100] = np.random.rand(100)

In [20]:
A[1,100:200] = A[0,:100]

In [21]:
A.setdiag(np.random.rand(1000))

In [22]:
A

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1199 stored elements in LInked List format>

**Algebra linear com matrizes esparsas**

In [23]:
from scipy.sparse import linalg

In [24]:
# Converte esta matriz para o formato linha esparsa comprimida.
A.tocsr()

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1199 stored elements in Compressed Sparse Row format>

In [25]:
A = A.tocsr()

In [26]:
b = np.random.rand(1000)

In [27]:
linalg.spsolve(A, b)

array([ -9.48409230e+01,  -1.14650838e+02,   1.01342056e+00,
         3.31645616e-01,   1.68192277e+00,   3.98473250e+00,
         3.29795631e-01,   2.76399263e-01,   2.38281381e+00,
         4.20495070e-03,   1.75945096e-01,   1.37917197e+00,
         7.20260409e+00,   1.02056801e+00,   2.59453591e-01,
         4.97125178e-01,   2.76386789e-01,   1.03718168e+00,
         1.41552025e+00,   4.53668051e-01,   4.27858976e-01,
         1.01319755e-01,   1.56313196e+00,   4.65507812e-03,
         1.69723799e+00,   5.88916047e-02,   4.63001022e-01,
         2.46772455e-01,   6.54672541e-01,   1.00381763e+00,
         3.50683140e-01,   5.80252729e-02,   5.33327852e+00,
         7.84771941e-01,   1.01157039e+00,   7.99707235e-01,
         1.38478606e+00,   1.85698779e+00,   5.05911006e-01,
         1.02360779e+00,   2.33648010e+00,   4.69476780e-01,
         9.39665939e-02,   2.93480513e-01,   3.15725170e-01,
         6.64136344e-01,   1.86048704e+00,   1.47939086e+00,
         8.82231127e-01,

Há muito mais que SciPy é capaz de, como Transformadas de Fourier, Funções de Bessel, etc ...

Dê uma olhada na Documentação para mais detalhes!